[build]
rustc-wrapper = "sccache"

[target.x86_64-unknown-linux-gnu]
linker = "rust-lld"

[profile.dev]
opt-level = 0
debug = true
incremental = true
codegen-units = 8

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
debug = false
strip = true

